version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily", time: "04:00" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "daily", time: "04:15" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]
    groups:
      docker-images:
        patterns: ["*"]